# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transfer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_reult = QtWidgets.QLabel(self.centralwidget)
        self.label_reult.setGeometry(QtCore.QRect(170, 10, 54, 12))
        self.label_reult.setObjectName("label_reult")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(490, 30, 231, 191))
        self.groupBox.setObjectName("groupBox")
        self.label_start = QtWidgets.QLabel(self.groupBox)
        self.label_start.setGeometry(QtCore.QRect(40, 100, 31, 16))
        self.label_start.setObjectName("label_start")
        self.slice_check = QtWidgets.QCheckBox(self.groupBox)
        self.slice_check.setGeometry(QtCore.QRect(10, 80, 51, 16))
        self.slice_check.setObjectName("slice_check")
        self.start = QtWidgets.QLineEdit(self.groupBox)
        self.start.setGeometry(QtCore.QRect(80, 100, 113, 20))
        self.start.setObjectName("start")
        self.label_end = QtWidgets.QLabel(self.groupBox)
        self.label_end.setGeometry(QtCore.QRect(40, 130, 31, 16))
        self.label_end.setObjectName("label_end")
        self.transfer_button = QtWidgets.QPushButton(self.groupBox)
        self.transfer_button.setGeometry(QtCore.QRect(150, 160, 75, 23))
        self.transfer_button.setObjectName("transfer_button")
        self.end = QtWidgets.QLineEdit(self.groupBox)
        self.end.setGeometry(QtCore.QRect(80, 130, 113, 20))
        self.end.setObjectName("end")
        self.name = QtWidgets.QLineEdit(self.groupBox)
        self.name.setGeometry(QtCore.QRect(80, 50, 113, 20))
        self.name.setObjectName("name")
        self.label_struct = QtWidgets.QLabel(self.groupBox)
        self.label_struct.setGeometry(QtCore.QRect(10, 50, 61, 20))
        self.label_struct.setObjectName("label_struct")
        self.label_note = QtWidgets.QLabel(self.centralwidget)
        self.label_note.setGeometry(QtCore.QRect(500, 260, 54, 12))
        self.label_note.setObjectName("label_note")
        self.text_note = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_note.setGeometry(QtCore.QRect(500, 270, 256, 192))
        self.text_note.setObjectName("text_note")
        self.text_result = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_result.setGeometry(QtCore.QRect(30, 30, 421, 501))
        self.text_result.setObjectName("text_result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_reult.setText(_translate("MainWindow", "转换结果"))
        self.groupBox.setTitle(_translate("MainWindow", "转换"))
        self.label_start.setText(_translate("MainWindow", "起始"))
        self.slice_check.setText(_translate("MainWindow", "切片"))
        self.label_end.setText(_translate("MainWindow", "结尾"))
        self.transfer_button.setText(_translate("MainWindow", "转换"))
        self.label_struct.setText(_translate("MainWindow", "结构体名称"))
        self.label_note.setText(_translate("MainWindow", "Note"))
        self.text_note.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">注意:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">地址必须进行4字节对齐</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">如果地址不连续会使用reserve补齐</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">可以使用切片功能对寄存器名进行截取</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">生成后的结果已经复制到剪贴板中直接粘贴即可</p></body></html>"))
